import { pipeline, getMetadata, replaceAudio, addSubtitles } from '../src/index.js';
import path from 'node:path';
import fs from 'node:fs/promises';
import { gradientOverlay, addText } from 'image-edit-tools';

/**
 * YouTube Shorts / TikTok Style Video Generator Example
 * 
 * Demonstrates:
 * 1. Using image-edit-tools to generate a dynamic background image
 * 2. Creating a 10-second video from that image using ffmpeg directly (or via convert hack)
 * 3. Adding background music (replaceAudio)
 * 4. Adding explanatory subtitles (addSubtitles)
 */
async function generateShorts() {
    console.log('🎬 Starting YouTube Shorts generation with image-edit-tools and BGM...');
    
    const examplesDir = process.cwd();
    const assetsDir = path.join(examplesDir, 'examples', 'assets');
    const bgmPath = path.join(assetsDir, 'Will You Still Love Me Tomorrow.mp3');
    const outputPath = path.join(examplesDir, 'examples', 'output-shorts.mp4');
    const tempVideoPath = path.join(examplesDir, 'tmp', 'shorts-temp.mp4');
    const bgImagePath = path.join(examplesDir, 'tmp', 'shorts-bg.png');
    
    // Ensure tmp dir exists
    await fs.mkdir(path.join(examplesDir, 'tmp'), { recursive: true });

    try {
        await fs.access(bgmPath);
    } catch {
        console.error(`❌ Background music missing at ${bgmPath}`);
        process.exit(1);
    }

    // 1. Create Background Image using image-edit-tools
    console.log('🖼️  Generating background image...');
    
    // Using raw Sharp since createBlankImage might not be exported from the installed version
    const sharp = (await import('sharp')).default;
    const blankBuffer = await sharp({
        create: {
            width: 1080,
            height: 1920,
            channels: 4,
            background: { r: 26, g: 26, b: 46, alpha: 1 } // #1a1a2e
        }
    }).png().toBuffer();

    // Add a cool gradient
    const withGradient = await gradientOverlay(blankBuffer, {
        direction: 'top',
        color: '#e94560',
        opacity: 0.6,
        coverage: 0.8
    });
    if (!withGradient.ok) throw new Error('Failed to add gradient');

    // Add title text using image-edit-tools which expects layers array
    const finalBg = await addText(withGradient.data, {
         layers: [{
             text: 'video-edit-tools\nSDK Demo',
             fontFamily: 'Arial',
             fontSize: 80,
             color: '#ffffff',
             x: 540,
             y: 400
         }]
    });
    if (!finalBg.ok) throw new Error('Failed to add text');
    
    await fs.writeFile(bgImagePath, finalBg.data as Buffer);

    // 2. We need to convert this single image into a 10-second video
    console.log('🎞️  Converting image to base video...');
    const Ffmpeg = (await import('fluent-ffmpeg')).default;
    await new Promise<void>((resolve, reject) => {
         Ffmpeg(bgImagePath)
            .loop(10) // 10 seconds
            .fps(30)
            .videoCodec('libx264')
            .format('mp4')
            .outputOptions(['-pix_fmt', 'yuv420p'])
            .save(tempVideoPath)
            .on('end', () => resolve())
            .on('error', (err) => reject(err));
    });

    // 3. Add Background Music (replaceAudio) and Subtitles via pipeline
    console.log('🎶 Adding Audio and 📝 Subtitles...');
    
    const srtContent = `1
00:00:01,000 --> 00:00:03,500
Welcome to video-edit-tools!

2
00:00:04,000 --> 00:00:06,500
This video was entirely generated by AI.

3
00:00:07,000 --> 00:00:09,500
Combining images, audio, and text easily.
`;

    // Write temp SRT
    const srtTempPath = path.join(examplesDir, 'tmp', 'shorts.srt');
    await fs.writeFile(srtTempPath, srtContent);

    // Run them in a chain (pipeline automatically passes output to next input)
    const result = await pipeline(tempVideoPath, [
        {
            op: 'replaceAudio',
            audio: bgmPath,
            fadeIn: 1,
            fadeOut: 2,
            loop: true
        },
        {
            op: 'addSubtitles',
            subtitles: srtTempPath,
            style: {
                 fontSize: 24,
                 color: '#ffffff',
                 outline: true,
                 position: 'bottom'
            }
        }
    ]);

    if (!result.ok) {
        console.error('❌ Failed to generate Shorts:', result.error);
        return;
    }

    // Save it
    await fs.writeFile(outputPath, result.data as Buffer);
    
    const meta = await getMetadata(outputPath);
    if (meta.ok) {
        console.log('✅ Success! YouTube Shorts video generated at:', outputPath);
        console.log(`📊 Video Stats: ${meta.data.width}x${meta.data.height}, ${meta.data.duration}s, ${meta.data.fps} FPS`);
    }

    // Cleanup
    await fs.unlink(tempVideoPath).catch(() => {});
    await fs.unlink(bgImagePath).catch(() => {});
    await fs.unlink(srtTempPath).catch(() => {});
}

generateShorts().catch(console.error);
